
  [[redirects]]
  from = "`https:api.github.com/users/${searchInput.trim()}`"
  to = "https://githubresearchguillaume.netlify.app/"
  status = 200
  force = true
  conditions = {Role = ["admin"]}
  [redirects.SearchBar]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
